name: Deploy

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ruby-version: 2.5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.ruby-version }}

    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: gems-${{ runner.os }}-${{ matrix.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          gems-${{ runner.os }}-${{ matrix.ruby-version }}-
          gems-${{ runner.os }}-

    - run: bundle config set deployment 'true'
    - name: bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - run: bundle exec middleman build

    - name: Deploy build to Server		
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:		
        username: '${{ secrets.USER }}'		
        server: '${{ secrets.HOST }}'		
        ssh_private_key: ${{ secrets.PRIVATE_KEY }}		
        local_path: './buid/*'		
        remote_path: 'Documentation/build'
        args: '-o ConnectTimeout=5'
